---

- name: Create user groups
  group:
    name: '{{ item.group | default(item.name) }}'
    system: '{{ item.system | default(omit) }}'
    gid: '{{ item.gid | default(omit) }}'
    state: 'present'
  with_flattened:
    - users_default
    - users_admins
    - users_groups
    - users_list
    - users_group_list
    - users_host_list
  when: ((item.name is defined and item.name and item.name != 'root') and
         (item.state is undefined or (item.state is defined and item.state != 'absent')))

- name: Manage user accounts
  user:
    name: '{{ item.name }}'
    uid: '{{ item.uid | default(omit) }}'
    group: '{{ item.group | default(item.name) }}'
    state: '{{ item.state | default("present") }}'
    comment: '{{ item.comment | default(omit) }}'
    password: '{{ item.password | default("*") }}'
    update_password: '{{ item.update_password | default("on_create") }}'
    system: '{{ item.system | default(omit) }}'
    shell: '{{ item.shell | default(omit) }}'
    home: '{{ item.home | default(omit) }}'
    createhome: '{{ item.createhome | default(omit) }}'
    expires: '{{ item.expires | default(omit) }}'
    remove: '{{ item.remove | default(omit) }}'
  with_flattened:
    - users_default
    - users_admins
    - users_list
    - users_group_list
    - users_host_list
  when: ((item.name is defined and item.name and item.name != 'root') and
         (item.state is undefined or (item.state is defined and item.state)))

- name: Manage user home directories
  file:
    path: '{{ item.home | default("~" + item.name) }}'
    state: 'directory'
    group: '{{ item.home_group | default(omit) }}'
    mode: '{{ item.home_mode | default(users_default_home_mode | default(omit)) }}'
  with_flattened:
    - users_default
    - users_admins
    - users_list
    - users_group_list
    - users_host_list
  when: ((item.name is defined and item.name and item.name != 'root') and
         (item.state is undefined or (item.state is defined and item.state)) and
         ((item.home_group is defined and item.home_group) or
          (users_default_home_mode is defined and users_default_home_mode) or
          (item.home_mode is defined and item.home_mode)))

- name: Get list of available groups
  shell: 'getent group | cut -f1 -d:'
  register: users_register_groups
  changed_when: False

- name: Manage user default groups
  user:
    name: '{{ item.name }}'
    state: '{{ item.state | default("present") }}'
    groups: '{{ (users_default_groups_list | intersect(users_register_groups.stdout_lines)) | join(",") }}'
    append: '{{ users_default_groups_append) }}'
  with_flattened:
    - users_default
    - users_admins
    - users_list
    - users_group_list
    - users_host_list
  when: ((item.name is defined and item.name and item.name != 'root') and
         (item.state is undefined or (item.state is defined and item.state != 'absent')) and
         (users_default_groups_list is defined and users_default_groups_list))

- name: Manage user groups
  user:
    name: '{{ item.name }}'
    state: '{{ item.state | default("present") }}'
    groups: '{{ (item.groups | intersect(users_register_groups.stdout_lines)) | join(",") }}'
    append: '{{ item.append | default("yes") }}'
  with_flattened:
    - users_default
    - users_admins
    - users_list
    - users_group_list
    - users_host_list
  when: ((item.name is defined and item.name and item.name != 'root') and
         (item.state is undefined or (item.state is defined and item.state != 'absent')) and
         (item.groups is defined and item.groups))

- name: Remove user groups if requested
  group:
    name: '{{ item.group | default(item.name) }}'
    state: 'absent'
  with_flattened:
    - users_default
    - users_admins
    - users_groups
    - users_list
    - users_group_list
    - users_host_list
  when: ((item.name is defined and item.name and item.name != 'root') and
         (item.state is defined and item.state == 'absent'))

